
CREATE SCHEMA `countries` ;

CREATE TABLE `countries`.`countries` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `flag` VARCHAR(100) NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `latitude` DECIMAL(8,4) NOT NULL,
  `longitude` DECIMAL(9,4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200),
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME ,
  PRIMARY KEY (`id`));


INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Andorra','AD','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg',42.546245,1.601554);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('United Arab Emirates','AE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg',23.424076,53.847818);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Afghanistan','AF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg',33.93911,67.709953);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Antigua & Barbuda','AG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg',17.060816,-61.796428);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Anguilla','AI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg',18.220554,-63.068615);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Albania','AL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg',41.153332,20.168331);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Armenia','AM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg',40.069099,45.038189);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Angola','AO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg',-11.202692,17.873887);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Antarctica','AQ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg',-75.250973,-0.071389);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Argentina','AR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg',-38.416097,-63.616672);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('American Samoa','AS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg',-14.270972,-170.132217);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Austria','AT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg',47.516231,14.550072);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Australia','AU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg',-25.274398,133.775136);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Aruba','AW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg',12.52111,-69.968338);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Azerbaijan','AZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg',40.143105,47.576927);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bosnia & Herzegovina','BA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg',43.915886,17.679076);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Barbados','BB','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg',13.193887,-59.543198);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bangladesh','BD','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg',23.684994,90.356331);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Belgium','BE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg',50.503887,4.469936);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Burkina Faso','BF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg',12.238333,-1.561593);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bulgaria','BG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg',42.733883,25.48583);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bahrain','BH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg',25.930414,50.637772);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Burundi','BI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg',-3.373056,29.918886);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Benin','BJ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg',9.30769,2.315834);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bermuda','BM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg',32.321384,-64.75737);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Brunei','BN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg',4.535277,114.727669);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bolivia','BO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg',-16.290154,-63.588653);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Brazil','BR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg',-14.235004,-51.92528);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bahamas','BS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg',25.03428,-77.39628);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bhutan','BT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg',27.514162,90.433601);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Bouvet Island','BV','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BV.svg',-54.423199,3.413194);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Botswana','BW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg',-22.328474,24.684866);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Belarus','BY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg',53.709807,27.953389);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Belize','BZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg',17.189877,-88.49765);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Canada','CA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg',56.130366,-106.346771);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cocos (Keeling) Islands','CC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg',-12.164165,96.870956);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Congo - Kinshasa','CD','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg',-4.038333,21.758664);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Central African Republic','CF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg',6.611111,20.939444);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Congo - Brazzaville','CG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg',-0.228021,15.827659);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Switzerland','CH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg',46.818188,8.227512);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Côte d’Ivoire','CI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg',7.539989,-5.54708);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cook Islands','CK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg',-21.236736,-159.777671);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Chile','CL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg',-35.675147,-71.542969);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cameroon','CM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg',7.369722,12.354722);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('China','CN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg',35.86166,104.195397);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Colombia','CO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg',4.570868,-74.297333);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Costa Rica','CR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg',9.748917,-83.753428);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cuba','CU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg',21.521757,-77.781167);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cape Verde','CV','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg',16.002082,-24.013197);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Christmas Island','CX','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg',-10.447525,105.690449);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cyprus','CY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg',35.126413,33.429859);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Czechia','CZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg',49.817492,15.472962);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Germany','DE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg',51.165691,10.451526);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Djibouti','DJ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg',11.825138,42.590275);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Denmark','DK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg',56.26392,9.501785);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Dominica','DM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg',15.414999,-61.370976);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Dominican Republic','DO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg',18.735693,-70.162651);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Algeria','DZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg',28.033886,1.659626);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Ecuador','EC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg',-1.831239,-78.183406);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Estonia','EE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg',58.595272,25.013607);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Egypt','EG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg',26.820553,30.802498);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Western Sahara','EH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg',24.215527,-12.885834);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Eritrea','ER','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg',15.179384,39.782334);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Spain','ES','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg',40.463667,-3.74922);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Ethiopia','ET','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg',9.145,40.489673);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Finland','FI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg',61.92411,25.748151);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Fiji','FJ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg',-16.578193,179.414413);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Falkland Islands','FK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg',-51.796253,-59.523613);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Micronesia','FM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg',7.425554,150.550812);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Faroe Islands','FO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg',61.892635,-6.911806);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('France','FR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg',46.227638,2.213749);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Gabon','GA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg',-0.803689,11.609444);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('United Kingdom','GB','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',55.378051,-3.435973);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Grenada','GD','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg',12.262776,-61.604171);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Georgia','GE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg',42.315407,43.356892);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('French Guiana','GF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg',3.933889,-53.125782);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Guernsey','GG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg',49.465691,-2.585278);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Ghana','GH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg',7.946527,-1.023194);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Gibraltar','GI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg',36.137741,-5.345374);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Greenland','GL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg',71.706936,-42.604303);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Gambia','GM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg',13.443182,-15.310139);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Guinea','GN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg',9.945587,-9.696645);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Guadeloupe','GP','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg',16.995971,-62.067641);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Equatorial Guinea','GQ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg',1.650801,10.267895);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Greece','GR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg',39.074208,21.824312);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('South Georgia & South Sandwich Islands','GS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GS.svg',-54.429579,-36.587909);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Guatemala','GT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg',15.783471,-90.230759);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Guam','GU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg',13.444304,144.793731);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Guinea-Bissau','GW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg',11.803749,-15.180413);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Guyana','GY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg',4.860416,-58.93018);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Hong Kong SAR China','HK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg',22.396428,114.109497);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Heard & McDonald Islands','HM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HM.svg',-53.08181,73.504158);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Honduras','HN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg',15.199999,-86.241905);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Croatia','HR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg',45.1,15.2);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Haiti','HT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg',18.971187,-72.285215);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Hungary','HU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg',47.162494,19.503304);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Indonesia','ID','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg',-0.789275,113.921327);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Ireland','IE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg',53.41291,-8.24389);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Israel','IL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg',31.046051,34.851612);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Isle of Man','IM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg',54.236107,-4.548056);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('India','IN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg',20.593684,78.96288);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('British Indian Ocean Territory','IO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IO.svg',-6.343194,71.876519);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Iraq','IQ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg',33.223191,43.679291);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Iran','IR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg',32.427908,53.688046);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Iceland','IS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg',64.963051,-19.020835);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Italy','IT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg',41.87194,12.56738);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Jersey','JE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg',49.214439,-2.13125);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Jamaica','JM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg',18.109581,-77.297508);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Jordan','JO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg',30.585164,36.238414);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Japan','JP','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg',36.204824,138.252924);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Kenya','KE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg',-0.023559,37.906193);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Kyrgyzstan','KG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg',41.20438,74.766098);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cambodia','KH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg',12.565679,104.990963);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Kiribati','KI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg',-3.370417,-168.734039);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Comoros','KM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg',-11.875001,43.872219);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('St. Kitts & Nevis','KN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg',17.357822,-62.782998);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('North Korea','KP','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg',40.339852,127.510093);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('South Korea','KR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg',35.907757,127.766922);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Kuwait','KW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg',29.31166,47.481766);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Cayman Islands','KY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg',19.513469,-80.566956);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Kazakhstan','KZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg',48.019573,66.923684);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Laos','LA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg',19.85627,102.495496);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Lebanon','LB','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg',33.854721,35.862285);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('St. Lucia','LC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg',13.909444,-60.978893);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Liechtenstein','LI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg',47.166,9.555373);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Sri Lanka','LK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg',7.873054,80.771797);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Liberia','LR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg',6.428055,-9.429499);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Lesotho','LS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg',-29.609988,28.233608);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Lithuania','LT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg',55.169438,23.881275);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Luxembourg','LU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg',49.815273,6.129583);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Latvia','LV','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg',56.879635,24.603189);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Libya','LY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg',26.3351,17.228331);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Morocco','MA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg',31.791702,-7.09262);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Monaco','MC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg',43.750298,7.412841);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Moldova','MD','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg',47.411631,28.369885);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Montenegro','ME','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg',42.708678,19.37439);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Madagascar','MG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg',-18.766947,46.869107);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Marshall Islands','MH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg',7.131474,171.184478);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('North Macedonia','MK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg',41.608635,21.745275);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Mali','ML','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg',17.570692,-3.996166);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Myanmar (Burma)','MM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg',21.913965,95.956223);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Mongolia','MN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg',46.862496,103.846656);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Macao SAR China','MO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg',22.198745,113.543873);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Northern Mariana Islands','MP','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg',17.33083,145.38469);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Martinique','MQ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg',14.641528,-61.024174);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Mauritania','MR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg',21.00789,-10.940835);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Montserrat','MS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg',16.742498,-62.187366);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Malta','MT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg',35.937496,14.375416);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Mauritius','MU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg',-20.348404,57.552152);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Maldives','MV','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg',3.202778,73.22068);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Malawi','MW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg',-13.254308,34.301525);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Mexico','MX','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg',23.634501,-102.552784);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Malaysia','MY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg',4.210484,101.975766);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Mozambique','MZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg',-18.665695,35.529562);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Namibia','NA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg',-22.95764,18.49041);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('New Caledonia','NC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg',-20.904305,165.618042);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Niger','NE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg',17.607789,8.081666);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Norfolk Island','NF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg',-29.040835,167.954712);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Nigeria','NG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg',9.081999,8.675277);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Nicaragua','NI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg',12.865416,-85.207229);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Netherlands','NL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg',52.132633,5.291266);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Norway','NO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg',60.472024,8.468946);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Nepal','NP','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg',28.394857,84.124008);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Nauru','NR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg',-0.522778,166.931503);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Niue','NU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg',-19.054445,-169.867233);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('New Zealand','NZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg',-40.900557,174.885971);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Oman','OM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg',21.512583,55.923255);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Panama','PA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg',8.537981,-80.782127);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Peru','PE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg',-9.189967,-75.015152);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('French Polynesia','PF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg',-17.679742,-149.406843);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Papua New Guinea','PG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg',-6.314993,143.95555);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Philippines','PH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg',12.879721,121.774017);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Pakistan','PK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg',30.375321,69.345116);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Poland','PL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg',51.919438,19.145136);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('St. Pierre & Miquelon','PM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg',46.941936,-56.27111);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Pitcairn Islands','PN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg',-24.703615,-127.439308);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Puerto Rico','PR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg',18.220833,-66.590149);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Palestinian Territories','PS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg',31.952162,35.233154);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Portugal','PT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg',39.399872,-8.224454);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Palau','PW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg',7.51498,134.58252);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Paraguay','PY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg',-23.442503,-58.443832);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Qatar','QA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg',25.354826,51.183884);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Réunion','RE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg',-21.115141,55.536384);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Romania','RO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg',45.943161,24.96676);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Serbia','RS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg',44.016521,21.005859);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Russia','RU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg',61.52401,105.318756);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Rwanda','RW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg',-1.940278,29.873888);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Saudi Arabia','SA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg',23.885942,45.079162);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Solomon Islands','SB','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg',-9.64571,160.156194);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Seychelles','SC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg',-4.679574,55.491977);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Sudan','SD','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg',12.862807,30.217636);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Sweden','SE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg',60.128161,18.643501);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Singapore','SG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg',1.352083,103.819836);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('St. Helena','SH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg',-24.143474,-10.030696);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Slovenia','SI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg',46.151241,14.995463);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Svalbard & Jan Mayen','SJ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg',77.553604,23.670272);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Slovakia','SK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg',48.669026,19.699024);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Sierra Leone','SL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg',8.460555,-11.779889);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('San Marino','SM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg',43.94236,12.457777);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Senegal','SN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg',14.497401,-14.452362);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Somalia','SO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg',5.152149,46.199616);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Suriname','SR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg',3.919305,-56.027783);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('São Tomé & Príncipe','ST','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg',0.18636,6.613081);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('El Salvador','SV','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg',13.794185,-88.89653);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Syria','SY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg',34.802075,38.996815);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Eswatini','SZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg',-26.522503,31.465866);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Turks & Caicos Islands','TC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg',21.694025,-71.797928);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Chad','TD','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg',15.454166,18.732207);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('French Southern Territories','TF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TF.svg',-49.280366,69.348557);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Togo','TG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg',8.619543,0.824782);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Thailand','TH','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg',15.870032,100.992541);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Tajikistan','TJ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg',38.861034,71.276093);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Tokelau','TK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg',-8.967363,-171.855881);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Timor-Leste','TL','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg',-8.874217,125.727539);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Turkmenistan','TM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg',38.969719,59.556278);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Tunisia','TN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg',33.886917,9.537499);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Tonga','TO','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg',-21.178986,-175.198242);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Turkey','TR','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg',38.963745,35.243322);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Trinidad & Tobago','TT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg',10.691803,-61.222503);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Tuvalu','TV','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg',-7.109535,177.64933);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Taiwan','TW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg',23.69781,120.960515);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Tanzania','TZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg',-6.369028,34.888822);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Ukraine','UA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg',48.379433,31.16558);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Uganda','UG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg',1.373333,32.290275);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('United States','US','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg',37.09024,-95.712891);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Uruguay','UY','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg',-32.522779,-55.765835);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Uzbekistan','UZ','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg',41.377491,64.585262);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Vatican City','VA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg',41.902916,12.453389);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('St. Vincent & Grenadines','VC','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg',12.984305,-61.287228);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Venezuela','VE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg',6.42375,-66.58973);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('British Virgin Islands','VG','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg',18.420695,-64.639968);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('U.S. Virgin Islands','VI','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg',18.335765,-64.896335);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Vietnam','VN','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg',14.058324,108.277199);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Vanuatu','VU','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg',-15.376706,166.959158);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Wallis & Futuna','WF','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg',-13.768752,-177.156097);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Samoa','WS','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg',-13.759029,-172.104629);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Kosovo','XK','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/XK.svg',42.602636,20.902977);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Yemen','YE','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg',15.552727,48.516388);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Mayotte','YT','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg',-12.8275,45.166244);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('South Africa','ZA','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg',-30.559482,22.937506);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Zambia','ZM','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg',-13.133897,27.849332);
INSERT INTO countries.countries(name,code,flag,latitude,longitude) VALUES ('Zimbabwe','ZW','https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg',-19.015438,29.154857);
